# Generated by Django 2.0.4 on 2018-04-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_scrapyitem_img_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapyitem',
            name='date',
        ),
    ]
