# Generated by Django 2.0.4 on 2018-04-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_scrapyitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapyitem',
            name='img_urls',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
