# Generated by Django 2.0.4 on 2018-04-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_scrapyitem_img_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapyitem',
            old_name='img_urls',
            new_name='image_urls',
        ),
    ]
